// AUTO-GENERATED by scripts/capture-claude-version.mjs — do not edit by hand.
// Captured from the build machine's installed Claude Code so the app can show which version
// it was built/tested against and warn before updating past it.
export const BUILT_AGAINST_CLAUDE_VERSION: string | null = '2.1.165'
export const BUILT_AGAINST_CAPTURED_AT = '2026-06-06T08:01:57.587Z'
